FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./analytics-data-center/cmd/analytics-data-center

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/server /usr/local/bin/server
COPY analytics-data-center/config ./config
ENV CONFIG_PATH=/app/config/docker.yaml
EXPOSE 8888
ENTRYPOINT ["/usr/local/bin/server"]

