version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      CONFIG_PATH: /app/config/docker.yaml
      MIGRATOR_STORAGE_PATH: ${MIGRATOR_STORAGE_PATH}
    ports:
      - "8888:8888"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
