env: "local"
storage_path: "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
dwh_db: "postgres"
dwh_db_path: "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
oltp_db: "postgres"
# oltp_db_path: "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
oltp_connections:
  - name: postgres
    connection_string: "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
  - name: postgres1
    connection_string: "postgresql://postgres:ohb5uvub3quaThah@10.0.30.7:5432/postgres?sslmode=disable"
token_ttl: 1h
grpc:
  port: 13890
  timeout: 10h
