env: "local"
log_lang: "ru"
storage_path: "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
# dwh_db: "postgres"
# dwh_db_path: "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
dwh_db: "clickhouse"
dwh_db_path: "clickhouse://username:password@localhost:9000/my_database"
oltp_db: "postgres"
# oltp_db_path: "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
oltp_connections:
  - name: postgres
    connection_string: "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
    connection_string_kafka: "postgresql://postgres:password@172.22.0.2:5432/postgres?sslmode=disable"
smtp_setting:
    host: "smtp.rambler.ru"
    port: 587
    username: "*********@rambler.ru"
    password: "*********"
    admin_email: "************@yandex.ru"
    from_email: "**********@rambler.ru"
token_ttl: 1h
kafka:
    bootstrap.servers: "localhost:9092"
    acks: "all"
    client_id: "debeziumConsumer"
    enable.auto.commit: "false"
    auto.offset.reset: "earliest"
    session.timeout.ms: "6000"
    group.id: "cdc-consumer-group"
kafka_connect: "http://localhost:8083"
grpc:
  port: 13890
  timeout: 11h
